version: '3'
services:
  jekyll:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/usr/src/app
    command: bundle exec jekyll serve -w --host 0.0.0.0
    environment:
      - RUBYOPT=-W0